spring:
  application:
    name: proxy-service

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    customer:
      path: /customer/**
      serviceId: customer-app
     
    customer1:
      path: /exlservice/**
      serviceId: exl-service
      
    customer2:
      path: /product/**
      serviceId: product-app
    
    customer3:
      path: /customer-app/**
      serviceId: customer-app
      
    customer4:
      path: /employee/**
      serviceId: employee-app
    